### ISSUE TITLE
Cannot access the gesture control in the web server 

### ISSUE THREAD

**Issue by minhduy105** [hrc2/blossom-public#2]
Hi, 
I tried to access the gesture control in the web server, but it did not show anything. In the terminal that I used to start the robot, it showed those lines 

 `
[2018-07-16 19:05:27,595] ERROR in app: Exception on /sequences [GET]
Traceback (most recent call last):`
`
File "/home/zi/wp/blossom/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request() `
`
File "/home/zi/wp/blossom/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)`
`
File "/home/zi/wp/blossom/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)`
`
File "/home/zi/wp/blossom/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()`
`
File "/home/zi/wp/blossom/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)`
`
File "/home/zi/wp/blossom/blossom-public/src/server.py", line 170, in get_sequences
    seqs = server.master_robot.get_time_sequences()`
`
AttributeError: 'SequenceRobot' object has no attribute 'get_time_sequences'`

The robot work fine with all of the video example, it just show those errors whenever I clicked on the "Gesture Control"
Finally, I am using VMWare to run the code in Linux.

Thank you,
~Duy

**Comment by psychomugs** [comment]
Pushed the missing functions, they should work now

**Comment by minhduy105** [comment]
Sorry for the late update. I just try it again and there is a few things happen
1) there are no errors shows up in my terminal 
2) the web browser is just a black page, there is no windows or anythings. (This is different than before you updated the code. Before it, I saw two windows in the browser, but there is no items in those windows)

**Comment by psychomugs** [comment]
Try running `yarn install` in the `blossom_web` directory?

**Comment by psychomugs** [comment]
I'm running similar versions, apart from a slightly newer version of Node (10.7).

You can't create new movements in Gesture Control, it's only there for playing gestures similar to typing them in the command line interface.

I added the code for the Expo application so that you can control the robot using the phone and make / record new gestures:
https://github.com/hrc2/blossom-public/tree/master/BlossomApp

**Comment by psychomugs** [comment]
Pushed updates to the control files; I'm currently out of town so I don't have an actual robot to test with but it seems to not throw errors testing just the app connected to the server.

To control the robot with the app, just move the phone around (screen up, with top of the screen pointing in the same direction as the front of the head so the robot should be facing away from you) and the head should follow the movements. The height and ears are controlled with the sliders. Press 'Reset Height' until the head and phone are aligned. You can also turn on 'Mirror' under 'Settings' to make it easier to control with the robot facing you instead of away.
