### ISSUE TITLE
Error from motor_calib.py

### ISSUE THREAD

**Issue by ashleysol2** [hrc2/blossom-public#39]
Hi all, I am trying to run the motor calibration script but I keep getting errors. Note that I used a U2D2 with a modified wire. I get this: 
Traceback (most recent call last):
  File "/Users/ashley/opt/anaconda3/lib/python3.7/site-packages/pypot/dynamixel/io/abstract_io.py", line 511, in __real_read
    header = self._protocol.DxlPacketHeader.from_string(data)
  File "/Users/ashley/opt/anaconda3/lib/python3.7/site-packages/pypot/dynamixel/protocol/v2.py", line 40, in from_string
    raise ValueError('try to parse corrupted data ({})'.format(header))
ValueError: try to parse corrupted data (bytearray(b'\x00'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "motor_calib.py", line 8, in <module>
    motor_id = motors.scan(range(20))
  File "/Users/ashley/opt/anaconda3/lib/python3.7/site-packages/pypot/dynamixel/io/abstract_io.py", line 221, in scan
    return [id for id in ids if self.ping(id)]
  File "/Users/ashley/opt/anaconda3/lib/python3.7/site-packages/pypot/dynamixel/io/abstract_io.py", line 221, in <listcomp>
    return [id for id in ids if self.ping(id)]
  File "/Users/ashley/opt/anaconda3/lib/python3.7/site-packages/pypot/dynamixel/io/abstract_io.py", line 214, in ping
    self._send_packet(pp, error_handler=None)
  File "/Users/ashley/opt/anaconda3/lib/python3.7/site-packages/pypot/dynamixel/io/abstract_io.py", line 527, in _send_packet
    return self.__real_send(instruction_packet, wait_for_status_packet, _force_lock)
  File "/Users/ashley/opt/anaconda3/lib/python3.7/site-packages/pypot/dynamixel/io/abstract_io.py", line 495, in __real_send
    status_packet = self.__real_read(instruction_packet, _force_lock=True)
  File "/Users/ashley/opt/anaconda3/lib/python3.7/site-packages/pypot/dynamixel/io/abstract_io.py", line 517, in __real_read
    raise DxlCommunicationError(self, msg, instruction_packet)
pypot.dynamixel.io.abstract_io.DxlCommunicationError: could not parse received data bytearray(b'\x00') after sending DxlPingPacket(id=0)

I tried using another modified wire and got this: 
Traceback (most recent call last):
  File "motor_calib.py", line 6, in <module>
    motors = pd.Dxl320IO(ports[0],1000000)
IndexError: list index out of range

Also keep getting: 
No connected motors found! Did you remember to connect external power?

Any advice? Thanks.

**Comment by psychomugs** [comment]
It looks like the motors are not being seen. How is the U2D2 modified? Could you send a picture of your wiring setup?
