### ISSUE TITLE
 Issue with Calibration of Ear and Tower Motors 

### ISSUE THREAD

**Issue by mbruttin** [hrc2/blossom-public#91]
Hi, 
I’ve successfully calibrated all the motors and completed building the Blossom robot. Now, I’m attempting to run the robot. However, I keep receiving this error message when I run "python3 start.py"

"
{'woody': {'controllers': {'my_dxl_controller': {'sync_read': False, 'attached_motors': ['tower', 'bases', 'head'], 'port': 'auto', 'baudrate': 1000000, 'protocol': 2}}, 'motorgroups': {'tower': ['tower_1', 'tower_2', 'tower_3'], 'bases': ['base'], 'head': ['ears']}, 'motors': {'tower_1': {'orientation': 'direct', 'type': 'XL-320', 'id': 1, 'angle_limit': [-150.0, 150.0], 'offset': 0.0}, 'tower_2': {'orientation': 'direct', 'type': 'XL-320', 'id': 2, 'angle_limit': [-150.0, 150.0], 'offset': 0.0}, 'tower_3': {'orientation': 'direct', 'type': 'XL-320', 'id': 3, 'angle_limit': [-150.0, 150.0], 'offset': 0.0}, 'base': {'orientation': 'direct', 'type': 'XL-320', 'id': 4, 'angle_limit': [-150.0, 150.0], 'offset': 0.0}, 'ears': {'orientation': 'direct', 'type': 'XL-320', 'id': 5, 'angle_limit': [50, 130.0], 'offset': 0.0}}}, 'test': {'controllers': {}, 'motorgroups': {}, 'motors': {}}}
configs,  [('woody', {'controllers': {'my_dxl_controller': {'sync_read': False, 'attached_motors': ['tower', 'bases', 'head'], 'port': 'auto', 'baudrate': 1000000, 'protocol': 2}}, 'motorgroups': {'tower': ['tower_1', 'tower_2', 'tower_3'], 'bases': ['base'], 'head': ['ears']}, 'motors': {'tower_1': {'orientation': 'direct', 'type': 'XL-320', 'id': 1, 'angle_limit': [-150.0, 150.0], 'offset': 0.0}, 'tower_2': {'orientation': 'direct', 'type': 'XL-320', 'id': 2, 'angle_limit': [-150.0, 150.0], 'offset': 0.0}, 'tower_3': {'orientation': 'direct', 'type': 'XL-320', 'id': 3, 'angle_limit': [-150.0, 150.0], 'offset': 0.0}, 'base': {'orientation': 'direct', 'type': 'XL-320', 'id': 4, 'angle_limit': [-150.0, 150.0], 'offset': 0.0}, 'ears': {'orientation': 'direct', 'type': 'XL-320', 'id': 5, 'angle_limit': [50, 130.0], 'offset': 0.0}}})]
general exception caught (please update the except statement with the exception) could not parse received data bytearray(b'\x00') after sending DxlPingPacket(id=0)
No motors found on /dev/tty.usbserial-1410
general exception caught (please update the except statement with the exception) could not parse received data bytearray(b'\x00') after sending DxlPingPacket(id=0)
No motors found on /dev/tty.usbserial-FT7928N5
returned {}
Traceback (most recent call last):
  File "/Users/MarineBruttin/blossom-public/start.py", line 620, in <module>
    main(parse_args(sys.argv[1:]))
  File "/Users/MarineBruttin/blossom-public/start.py", line 551, in main
    master_robot = safe_init_robot(args.names[0], configs[args.names[0]])
KeyError: 'woody'
MarineBruttin@MacBook-Pro-4 blossom-public % sudo chmod 777 blossom-public /dev/tty.usbserial-FT7928N5
chmod: blossom-public: No such file or directory"

Has anyone encountered this issue or have any suggestions on how to resolve it? Any help would be greatly appreciated!
Thank you in advance!
Marine

Please find below pictures of my setting :)
![IMG_1345](https://github.com/user-attachments/assets/2aa15011-203c-483e-9376-0cb92ce5c147)
![IMG_1346](https://github.com/user-attachments/assets/f8aad2de-74f8-4b47-a9a4-d11b1af87806)
![IMG_1348](https://github.com/user-attachments/assets/e3e99fd7-35b0-44c4-944f-f6670c720a73)

**Comment by msgtn** [comment]
Hi @mbruttin ,

It seems that there's an extra space in `sudo chmod 777 blossom-public /dev/tty.usbserial-FT7928N5`, after `blossom-public` and before `/dev...`. Can you try removing that space:
```
sudo chmod 777 blossom-public/dev/tty.usbserial-FT7928N5
```
